language: minimal
os: linux
dist: xenial

addons:
  apt:
    sources:
    - sourceline: 'ppa:mhier/libboost-latest'
    - sourceline: 'ppa:beineri/opt-qt-5.14.1-xenial'
    - sourceline: 'ppa:savoury1/backports'
    packages:
    - curl
    - gcc
    - g++
    - make
    - autoconf
    - automake
    - pkg-config
    - file
    - libgl1-mesa-dev
    - zlib1g-dev
    - libssl-dev
    - libtool
    - qt514base
    - qt514svg
    - qt514tools
    - libboost1.70-dev

install:
- source /opt/qt514/bin/qt514-env.sh

script:
- mkdir -p /tmp/libtorrent-rasterbar
- |
  [ -f /tmp/libtorrent-rasterbar/.unpack_ok ] || \
      curl -ksSfL https://github.com/arvidn/libtorrent/archive/HEAD.tar.gz | \
      tar -zxf - -C /tmp/libtorrent-rasterbar --strip-components 1
- touch "/tmp/libtorrent-rasterbar/.unpack_ok"
- cd "/tmp/libtorrent-rasterbar/"
- CXXFLAGS="-std=c++14" CPPFLAGS="-std=c++14" ./bootstrap.sh --prefix=/usr --with-boost-libdir="/usr/lib" --disable-debug --disable-dependency-tracking --disable-silent-rules --disable-maintainer-mode --with-libiconv
- make clean
- make -j$(nproc) V=0
- sudo make uninstall
- sudo make install
- cd "${TRAVIS_BUILD_DIR}"
- ./configure --prefix=/tmp/qbee/AppDir/usr --with-boost-libdir="/usr/lib" || (cat config.log && exit 1)
- make install -j$(nproc)
- '[ -x "/tmp/linuxdeploy-x86_64.AppImage" ] || curl -LC- -o /tmp/linuxdeploy-x86_64.AppImage "https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage"'
- '[ -x "/tmp/linuxdeploy-plugin-qt-x86_64.AppImage" ] || curl -LC- -o /tmp/linuxdeploy-plugin-qt-x86_64.AppImage https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage'
- chmod -v +x '/tmp/linuxdeploy-plugin-qt-x86_64.AppImage' '/tmp/linuxdeploy-x86_64.AppImage'
- cd "/tmp/qbee"
- mkdir -p "/tmp/qbee/AppDir/apprun-hooks/"
- echo 'export XDG_DATA_DIRS="${APPDIR:-"$(dirname "${BASH_SOURCE[0]}")/.."}/usr/share:${XDG_DATA_DIRS}:/usr/share:/usr/local/share"' > "/tmp/qbee/AppDir/apprun-hooks/xdg_data_dirs.sh"
- APPIMAGE_EXTRACT_AND_RUN=1 UPDATE_INFORMATION="zsync|https://github.com/${TRAVIS_REPO_SLUG}/releases/latest/download/qBittorrent-Enhanced-Edition.AppImage.zsync" OUTPUT='qBittorrent-Enhanced-Edition.AppImage' /tmp/linuxdeploy-x86_64.AppImage --appdir="/tmp/qbee/AppDir" --output=appimage --plugin qt

deploy:
  provider: releases
  overwrite: true
  api_key: "${GITHUB_TOKEN}"
  file:
  - qBittorrent-Enhanced-Edition.AppImage
  - qBittorrent-Enhanced-Edition.AppImage.zsync
  on:
    all_branches: true
    tags: true
